### ISSUE TITLE
Předávat velké parametry const-referencí

### ISSUE THREAD

**Issue by fan1x** [exyi/cpp-img2audio#1]
Např:

https://github.com/exyi/cpp-img2audio/blob/4a97f233782a76bd0758e4b37f45d030d89b9093/text2lines.hpp#L220

https://github.com/exyi/cpp-img2audio/blob/4a97f233782a76bd0758e4b37f45d030d89b9093/text2lines.hpp#L234

**Comment by exyi** [comment]
Jo, to jsem moc neřešil, vzhledem k tomu, že na každý char je potom potřeba vygenerovat řádově sekundu WAVu :)

Ale ono je v tomto případě asi stejně lepší brát `string_view`, že?
