### ISSUE TITLE
Použít switch-case

### ISSUE THREAD

**Issue by fan1x** [exyi/cpp-img2audio#3]
Proč nepoužít switch?

https://github.com/exyi/cpp-img2audio/blob/4a97f233782a76bd0758e4b37f45d030d89b9093/text2lines.hpp#L7

**Comment by exyi** [comment]
Protože má AFAIK implicitní fall-through, takže je náchylnější na chyby. Navíc nevím jak ho odsazovat nelíbí se mi ta syntaxe...

**Comment by fan1x** [comment]
Tak on ti normální překladač většinou vynadá, když můžeš udělat fall-through. IMHO, kdy jindy chtít použít switch než v tomhle případě -> na hodnoty abecedy...

Btw, nejhezčí by to bylo s OOP -> udělat si objekty, které to budou mít v sobě a nemusíš tam mít takové monstrum `if-else`
