### ISSUE TITLE
Vážně je php a shell lepší než C++

### ISSUE THREAD

**Issue by fan1x** [exyi/cpp-img2audio#5]
Vážně je php a shell lepší/čistější? než C++? 🤣 
U jiných jazyků to beru - Rust, ale ty dvě věci, jsou imho celkem zrůdnost...
Co bys navrhoval místo toho?  Chceme naučit studenty programovat v nějakém low-level jazyku a to jsou dneska v praxi víceméně prostě jen C/C++. Rust možná vypadá slibně, ale zatím ho skoro nikde nepoužívají... 😢 

https://github.com/exyi/cpp-img2audio/blob/4a97f233782a76bd0758e4b37f45d030d89b9093/soundobjects.hpp#L55

**Comment by exyi** [comment]
Shell není čistčí, ale snáz se používá a když se něco rozbije, tak se dobře hledá. Na druhou stranu se v tom nedá napsat nic správně, o čemž jsem se ale nezmiňoval.

PHP je má oproti C++ systematicky navržený typový systém (i když to ten shell taky :D), snadno se chápe sémantika a když se něco rozbije tak se to taky dobře debuguje (a jak nerad to o PHP říkám...). Možná se za to platí dynamickými typy a GC, ale lepší než drátem do oka. Sice má PHP pitomé implicitní konverze a blblou standardní knihovnu, ale oproti C++ je to ještě pohádka. Alespoň je nenapadlo dělat by default z konstruktoru implicitní konverzi...

A speciálně Javascriptu jsem si fakt začal vážit až po tom co mi ukázali pár hezkých věci na MFF...

**Comment by fan1x** [comment]
> Alespoň je nenapadlo dělat by default z konstruktoru implicitní konverzi...
Můžeš použít `explicit` 😉 

Souhlasím s tím, že C++ není jazyk, kde chceš psát něco, abys to měl rychle naprogramované - prototypovat. Poměr C++ vs. třeba C#/Java bude hodně špatnej. 

Prostě každej jazyk má svojí cílovku - nechceš asi v Javascriptu psát OS a nadruhou stranu asi nechceš psát v C++ web...
