### ISSUE TITLE
Nestačil by unique_ptr?

### ISSUE THREAD

**Issue by fan1x** [exyi/cpp-img2audio#6]
https://github.com/exyi/cpp-img2audio/blob/eacd638941494b647109d1c8233bae06005f3ecd/soundobjects.hpp#L18

**Comment by exyi** [comment]
To by pak funkce jako `move_start` a `normalize_volume` nemohly být const. Buď by musely sežrat celý objekt (což s C++ `move` sémantikou zrovna dobře nejde) a nebo ho měnit. https://github.com/exyi/cpp-img2audio/blob/eacd638941494b647109d1c8233bae06005f3ecd/soundobjects.hpp#L30

Někdy jsem tam i používal to, že byl několikrát přidaný zvuk se stejným původním bufferem, ale napamatuju si, jestli jsem to zase neodstranil.

Co jsem pochopil, tak shared_ptr není moc drahý a cyklické reference tam nemám, takže by měl být i bezpečný. Nebo je tam nějaká další past?

**Comment by fan1x** [comment]
Spíš je zbytečné používat `shared_ptr`, když stačí `unique_ptr`. Máš tam drobíček overhead, ale jinak je to jedno. 
V tvém případě je to ok asi.
