### ISSUE TITLE
Použít C++ casting

### ISSUE THREAD

**Issue by fan1x** [exyi/cpp-img2audio#8]
Já vím, je to otrava... C++ casting je schválně dlouhej a otrava, protože je to něco, co by se mělo využívat minimálně a mělo by to být v kódu vidět.

https://github.com/exyi/cpp-img2audio/blob/eacd638941494b647109d1c8233bae06005f3ecd/sinethetizers.hpp#L11

**Comment by exyi** [comment]
Předpokládám, že správná C++ková cesta je nikdy nepoužívat explicitní konverzi, když jsou stejně všechny implicitní :P

**Comment by fan1x** [comment]
No, ono se bez konverze občas neobejdeš tak pokud chceš udělat converzi, tak prostě použiješ nějaký cast, tady v tom případě například `static_cast`, tedy: `return static_cast<f32>(sin(pos / 0.03 * M_PI / 2));`

C-čková konverze není moc dobrá, protože vlastně zkouší postupně všechny konverze - ty nechceš ideálně používat takový nástroj.

**Comment by exyi** [comment]
Tak v tomto případě by mělo stačit použít `f32` jako funkci, ne?

Jinak jsem to stejně změnil, aby to vůbec `f64` nepoužívalo, protože je to zbytečné.

**Comment by fan1x** [comment]
Ano, v tomhle případě ani není potřeba.
