### ISSUE TITLE
Vyhazovát správě výjimky

### ISSUE THREAD

**Issue by fan1x** [exyi/cpp-img2audio#9]
Tahle výjimka je vyhozená jako `const char *`, což se převede na int -> správně si vytvoř vlastní výjimku nebo vyhazuj `std::runtime_error()` apod.

https://github.com/exyi/cpp-img2audio/blob/eacd638941494b647109d1c8233bae06005f3ecd/soundobjects.hpp#L23

**Comment by exyi** [comment]
Aha, možná proto se to chovalo tak retardovaně :D, jsem si myslel, že můžu vyhodit string jako v Javascriptu. 

Operaveno (společně s ostatními výjimkami): 3426ae90f37c2b367687a1ff184aad851e6a73dd
